Sprint 3
RX-ON/middle.messenger.praktikum.yandex pull request #3
Opened 2022-03-08 20:02 UTC by RX-ON

Здравствуйте! Данный спринт дался мне особенно тяжело. Я постарался сделать всё самое основное. Очень сильно горят сроки. Ввиду своей занятости у меня остаётся очень мало времени на учёбу, но я не собираюсь сдаваться! В процессе работы над практикой третьего спринта я понял, что проект надо переписать, так как реактивность не работала, вот прям совсем... Переписал! Все заработало так, как должно было изначально. Далее я стал выполнять задания по списку. К сожалению, я не успел написать хотя бы один тест, но я обязательно исправлюсь! Открыт к любой критике. Хотел бы Вас попросить не судить работу строго - действительно очень мало времени было. Тесты и адекватную типизацию я допишу позже. Заранее благодарю за проверку!

2022-03-11 07:16 UTC, ivan-infro commented
Необходимо чтобы все автоматические проверки проходили успешно, сейчас в package.json не хватает @parcel/config-default

> 2 |   "extends": "@parcel/config-default",
>   |              ^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/config-default"

2022-03-11 07:37 UTC, ivan-infro commented
Корректный почтовый адрес mail@example.games не проходит валидацию

https://habr.com/ru/post/274985/
https://habr.com/ru/post/175375/
Valid email addresses
[simple@example.com](mailto:simple@example.com)
[very.common@example.com](mailto:very.common@example.com)
[disposable.style.email.with+symbol@example.com](mailto:disposable.style.email.with+symbol@example.com)
[other.email-with-hyphen@example.com](mailto:other.email-with-hyphen@example.com)
[fully-qualified-domain@example.com](mailto:fully-qualified-domain@example.com)
[user.name+tag+sorting@example.com](mailto:user.name+tag+sorting@example.com) (may go to [user.name@example.com](mailto:user.name@example.com) inbox depending on mail server)
[x@example.com](mailto:x@example.com) (one-letter local-part)
[example-indeed@strange-example.com](mailto:example-indeed@strange-example.com)
test/[test@test.com](mailto:test@test.com) (slashes are a printable character, and allowed)
admin@mailserver1 (local domain name with no [TLD](https://en.wikipedia.org/wiki/Top-level_domain), although ICANN highly discourages dotless email addresses[[10]](https://en.wikipedia.org/wiki/Email_address#cite_note-12))
example@s.example (see the [List of Internet top-level domains](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains))
" "@example.org (space between the quotes)
"john..doe"@example.org (quoted double dot)
mailhost![username@example.org](mailto:username@example.org) (bangified host route used for uucp mailers)
[user%example.com@example.org](mailto:user%example.com@example.org) (% escaped mail route to [user@example.com](mailto:user@example.com) via [example.org](http://example.org/))
[user-@example.org](mailto:user-@example.org) (local part ending with non-alphanumeric character from the list of allowed printable characters)
postmaster@[123.123.123.123] (IP addresses are allowed instead of domains when in square brackets, but strongly discouraged)
postmaster@[IPv6:2001:0db8:85a3:0000:0000:8a2e:0370:7334] (IPv6 uses a different syntax)

2022-03-11 07:40 UTC, ivan-infro commented
Форма авторизации не выводит ошибки, возвращаемые сервером
<img width="1364" alt="Screenshot 2022-03-11 at 10 39 43" src="https://user-images.githubusercontent.com/5419627/157823655-424afc06-3d9c-4895-ab8a-c3f9bde681f4.png">

2022-03-11 07:50 UTC, ivan-infro commented
`npm run eslint` завершается с ошибкой
✖ 28 problems (9 errors, 19 warnings)

2022-03-11 07:51 UTC, ivan-infro commented
Тесты - обязательное условие 3го спринта, необходимо их написать

2022-03-11 07:52 UTC, ivan-infro requested changes

2022-03-11 07:52 UTC, ivan-infro commented on src/common/scripts/v2/Block.ts
> +// import Handlebars from 'handlebars';
Старайтесь не хранить закомментированный код в репозитории, это ухудшает читаемость

2022-03-11 07:52 UTC, ivan-infro commented on src/common/scripts/v2/Block.ts
> +		this.getContent().style.display = 'block';
Элемент мог быть изначально не блочным (например, span по умолчанию имеет display: inline)
Рекомендую скрывать элемент путем добавления/удаления class, а не изменением инлайн стилей

2022-03-11 07:52 UTC, ivan-infro commented on src/common/scripts/v2/Router/Route.ts
> +			this.block.hide();
При покидании страницы, она должна полностью удаляться из DOM. В противном случае после долгой навигации по приложению DOM дерево разрастется очень сильно и будут возникать лишние события

2022-03-11 07:52 UTC, ivan-infro commented on src/common/scripts/v2/Store/Actions.ts
> +        // eslint-disable-next-line no-console
Избегайте отключающие проверки комментарии, это может привести к замалчиванию реальной ошибки

2022-03-11 21:56 UTC, RX-ON commented on src/common/scripts/v2/Block.ts
> +// import Handlebars from 'handlebars';
Постарался максимально почистить проект.

2022-03-11 21:58 UTC, RX-ON commented on src/common/scripts/v2/Block.ts
> +		this.getContent().style.display = 'block';
Старался делать согласно той теории, что мне преподносили в практикуме. С замечанием полностью согласен. Я перепишу эту логику позже, так как моя цель сейчас - сделать необходимый минимум и наконец приступить к 4му спринту, времени очень мало.

2022-03-11 21:59 UTC, RX-ON commented on src/common/scripts/v2/Router/Route.ts
> +			this.block.hide();
Насчёт этого момента я обращался к наставнику. Он сказал, что для тестового проекта этого будет достаточно. Мне тоже не нравится, как это работает сейчас, но время играет против меня.

2022-03-11 22:00 UTC, RX-ON commented on src/common/scripts/v2/Store/Actions.ts
> +        // eslint-disable-next-line no-console
Лишний console.log почистил.

2022-03-11 22:07 UTC, RX-ON commented
Добавил @parcel/config-default в package.json.
Поправил валидацию email`a - делал её чётко по ТЗ ко второму спринту, прошлый ревьювер её пропустил. Я действительно с радостью бы окунулся в регулярки или последовал примеру из стать, которую Вы скинули, но я совсем не успеваю, ещё и проверка сильно затянулась, в общем - всё пошло не по плану. Из-за этого мне приходилось где-то экономить время, каюсь. 
Сделал вывод в интерфейс ошибок, пришедших с сервера.
Поправил все огрехи, подсвеченные eslint`ом.
Написал тесты.

2022-03-11 22:14 UTC, RX-ON commented
Выражаю благодарность за Вашу работу. Я извиняюсь за наглость, но хотел бы Вас попросить не судить строго. У меня осталось очень мало времени, чтобы закрыть 4й спринт. Если грубых ошибок нет - пропустите меня дальше.

2022-03-13 18:34 UTC, RX-ON commented
Очень долгая проверка, очень... Извините, не могли бы Вы объяснить, как происходит распределение работ для их проверки? Работаете ли Вы по выходным? Хоть какая-нибудь информация... Я не могу терять столько времени впустую!

2022-03-16 19:51 UTC, merged